export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const RESET_AUTH = 'RESET_AUTH';
export const AUTH_FROM_TOKEN = 'AUTH_FROM_TOKEN';

export const REQUEST_SUCCESS_MESSAGE = 'REQUEST_SUCCESS_MESSAGE';
export const REQUEST_ERROR_MESSAGE = 'REQUEST_ERROR_MESSAGE';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';

export const SET_AUTH_NAV = 'SET_AUTH_NAV';
export const SET_DEFAULT_NAV = 'SET_DEFAULT_NAV';

export const UPDATE_TITLE = 'UPDATE_TITLE';

export const REQUEST_QUOTES = 'REQUEST_QUOTES';
export const RECIEVE_QUOTES = 'RECIEVE_QUOTES';
export const RECIEVE_ERROR = 'RECIEVE_ERROR';
 
export const REQUEST_QUOTE_DATA = 'REQUEST_QUOTE_DATA';
export const RECIEVE_QUOTE_DATA = 'RECIEVE_QUOTE_DATA';

export const RECIEVE_QUOTE_HIST_DAY = 'RECIEVE_QUOTE_HIST_DAY';
export const RECIEVE_QUOTE_HIST_WEEK = 'RECIEVE_QUOTE_HIST_WEEK';
export const RECIEVE_QUOTE_HIST_MONTH = 'RECIEVE_QUOTE_HIST_MONTH';
export const RECIEVE_QUOTE_HIST_YEAR = 'RECIEVE_QUOTE_HIST_YEAR';
export const RECIEVE_QUOTE_HIST_THREE_MONTH = 'RECIEVE_QUOTE_HIST_THREE_MONTH';
export const RECIEVE_QUOTE_HIST_THREE_YEAR = 'RECIEVE_QUOTE_HIST_THREE_YEAR';
export const RECIEVE_QUOTE_HIST_ALL = 'RECIEVE_QUOTE_HIST_ALL';

export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const RECIEVE_USER_DATA = 'RECIEVE_USER_DATA';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';

export const REQUEST_USER_STOCKS = 'REQUEST_USER_STOCKS';
export const RECIEVE_USER_STOCKS = 'RECIEVE_USER_STOCKS';

export const REQUEST_USER_STOCK_ADD = 'REQUEST_USER_STOCK_ADD';
export const RECIEVE_USER_STOCK_ADD = 'RECIEVE_USER_STOCK_ADD';
export const REQUEST_USER_STOCK_DELETE = 'REQUEST_USER_STOCK_DELETE';
export const RECIEVE_USER_STOCK_DELETE = 'RECIEVE_USER_STOCK_DELETE';