export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const RESET_AUTH = 'RESET_AUTH';
export const AUTH_FROM_TOKEN = 'AUTH_FROM_TOKEN';

export const REQUEST_SUCCESS_MESSAGE = 'REQUEST_SUCCESS_MESSAGE';
export const REQUEST_ERROR_MESSAGE = 'REQUEST_ERROR_MESSAGE';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';

export const SET_AUTH_NAV = 'SET_AUTH_NAV';
export const SET_DEFAULT_NAV = 'SET_DEFAULT_NAV';

